const state={devices:[],incidents:[],health:null};
const rooms=[{name:"Living",icon:"◫",temp:"21.5°",detail:"6 dispositivi · Luci accese"},{name:"Cucina",icon:"◒",temp:"20.8°",detail:"4 dispositivi · Tutto spento"},{name:"Camera",icon:"☾",temp:"20.2°",detail:"5 dispositivi · Comfort notte"},{name:"Studio",icon:"□",temp:"21.1°",detail:"3 dispositivi · Scrivania attiva"},{name:"Bagno",icon:"≈",temp:"22.0°",detail:"2 dispositivi · Umidità 52%"},{name:"Terrazza",icon:"○",temp:"18.4°",detail:"3 dispositivi · Porta chiusa"}];
const titles={home:"Buonasera, Nicolas",ambienti:"I tuoi ambienti",sicurezza:"Sicurezza e affidabilità",energia:"Energia intelligente"};

function navigate(view){document.querySelectorAll('.view').forEach(el=>el.classList.toggle('active',el.id===`${view}-view`));document.querySelectorAll('.nav-item').forEach(el=>el.classList.toggle('active',el.dataset.view===view));document.getElementById('page-title').textContent=titles[view];history.replaceState(null,'',`#${view}`);window.scrollTo({top:0,behavior:'smooth'});}
document.querySelectorAll('[data-view]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.view)));
document.querySelectorAll('[data-target]').forEach(el=>el.addEventListener('click',()=>navigate(el.dataset.target)));

function renderRooms(){const compact=rooms.slice(0,3).map(r=>`<div class="room-row"><div class="room-name"><span class="room-thumb">${r.icon}</span><div class="row-copy"><strong>${r.name}</strong><small>${r.detail}</small></div></div><span class="room-temp">${r.temp}</span></div>`).join('');document.getElementById('room-preview').innerHTML=compact;document.getElementById('rooms-grid').innerHTML=rooms.map(r=>`<article class="room-card"><span class="eyebrow">${r.icon} AMBIENTE</span><div class="room-meta"><div><h3>${r.name}</h3><p>${r.detail}</p></div><b>${r.temp}</b></div></article>`).join('');}
function renderEvents(){const events=state.incidents.slice(0,4).map(i=>({title:i.title,detail:i.status==='resolved'?'Incidente risolto':'Richiede attenzione',time:i.opened_at?new Date(i.opened_at).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'}):'Ora'}));if(!events.length)events.push({title:'Sistema verificato',detail:'Tutti i servizi rispondono correttamente',time:'Ora'},{title:'Sicurezza perimetrale',detail:'Monitoraggio attivo',time:'18:42'});document.getElementById('event-list').innerHTML=events.map(e=>`<div class="event-row"><div class="event-main"><span class="event-dot"></span><div class="row-copy"><strong>${e.title}</strong><small>${e.detail}</small></div></div><time>${e.time}</time></div>`).join('');}
function renderIncidents(){const root=document.getElementById('incidents-list');if(!state.incidents.length){root.innerHTML='<div class="empty-state">Nessun incidente registrato. La casa è protetta.</div>';return}root.innerHTML=state.incidents.map(i=>`<div class="incident-row"><div class="row-copy"><strong>${i.title}</strong><small>${i.entity_id} · ${i.status}</small></div><span class="severity">${i.severity}</span></div>`).join('');}
async function json(url,fallback){try{const response=await fetch(url);if(!response.ok)throw new Error(response.status);return await response.json()}catch(error){console.warn(`DOMUS: ${url} non disponibile`,error);return fallback}}
async function refresh(){const [status,devices,incidents,health]=await Promise.all([json('/api/v1/status',null),json('/api/v1/devices',[]),json('/api/v1/incidents',[]),json('/api/v1/ha/health',null)]);state.devices=devices;state.incidents=incidents;state.health=health;const available=devices.filter(d=>d.is_available).length;const open=incidents.filter(i=>i.status==='open');const serviceState=status?'Online':'Non raggiungibile';document.getElementById('system-version').textContent=`DOMUS ${status?.version??'—'} · ${serviceState}`;document.getElementById('device-count').textContent=devices.length||'—';document.getElementById('device-subtitle').textContent=devices.length?`${available} online`:'In attesa di dispositivi';document.getElementById('health-score').textContent=health?.score??'—';document.getElementById('active-incidents').textContent=health?.active_incidents??open.length;document.getElementById('offline-devices').textContent=health?.offline_devices??devices.filter(d=>!d.is_available).length;document.getElementById('watchdog-state').textContent=health?.watchdog_status??'—';document.getElementById('security-state').textContent=open.length?'Attenzione':health?'Attiva':'Non disponibile';document.getElementById('security-title').textContent=open.length?'Controllo richiesto':health?'Casa protetta':'Backend non raggiungibile';document.getElementById('incident-summary').textContent=open.length?`${open.length} avvisi attivi`:health?'Nessun avviso':'Dati non disponibili';document.getElementById('last-update').textContent=`Aggiornato alle ${new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'})}`;renderEvents();renderIncidents()}
document.getElementById('scene-button').addEventListener('click',event=>{event.currentTarget.classList.toggle('active');event.currentTarget.textContent=event.currentTarget.classList.contains('active')?'Scena attiva ✓':'Attiva scena'});
function updateClock(){document.getElementById('clock').textContent=new Date().toLocaleString('it-IT',{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}
renderRooms();updateClock();setInterval(updateClock,30000);refresh();setInterval(refresh,60000);navigate(location.hash.slice(1) in titles?location.hash.slice(1):'home');
